language: python

dist: focal

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9
      dist: bionic
    - python: 3.10
      dist: bionic

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements-travis.txt
  - python3 setup.py install

env:
  - CI=true

script:
  - pytest -v --cov -c pytest-travisci.ini tests

after_success:
  - codecov

notifications:
  email: false